# Everything in this section will be available as an environment variable 
admin_username = "Jane"
admin_password = "12345qwerty"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.   
[database]
list_data = ["Streamlit", "Python"]
db_user = "sql_admin"
db_pass = "321_zeaed"